. /etc/defaults/rc.conf

rc_configured=YES
hostname=netbsd-vz
no_swap=YES
auto_ifconfig=NO
dhcpcd=NO
inetd=NO
postfix=NO
sshd=NO

case " $(/sbin/ifconfig -l 2>/dev/null) " in
    *" vioif"*)
        dhcpcd=YES
        dhcpcd_flags="-qM --waitip=4 --timeout 30"
        ;;
esac
